eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    instance-id: IMCP-BCMS-2020
    prefer-ip-address: true
server:
  port: 2020
spring:
  application:
    name: IMCP-BCMS
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/imcp_bcms?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: root
logging:
    config: classpath:logback-spring.xml