eureka:
    client:
        serviceUrl:
            defaultZone: http://imcp-eureka-8761.com:8761/eureka,http://imcp-eureka-8762.com:8762/eureka,http://imcp-eureka-8763.com:8763/eureka
    instance:
        instance-id: imcp-basic-2010.com # 在信息列表时显示主机名称   #host 文件需要配置  127.0.0.1 imcp-basic-2010.com
        lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
        lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
        prefer-ip-address: true     # 访问的路径变为IP地址
logging:
    config: classpath:logback-spring.xml
mybatis:
    mapper:
        identity: MYSQL
        mappers: com.imcp.basic.mapper
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.imcp.basic.bean
server:
    port: 2010
spring:
    application:
        name: IMCP-BASIC
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/imcp_basic?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: root
#    security:
#      basic:
#        enabled: true # 启用SpringSecurity的安全配置项
#      user:
#        name: imcp  # 认证用户名
#        password: 123456 # 认证密码
#        role:        # 授权角色
#        - USER
