eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
    instance:
        instance-id: IMCP-BASIC-2010
        prefer-ip-address: true
logging:
    config: classpath:logback-spring.xml
mybatis:
    mapper-locations: classpath:mapper/*.xml
    #实体类所在包名
    type-aliases-package: com.imcp.basic.bean
    #通用mapper配置
    mapper:
        #公用接口类路径
        mappers: com.imcp.basic.mapper
        identity: MYSQL
server:
    port: 2010
spring:
    application:
        name: IMCP-BASIC
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/imcp_basic?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: root
