/*
Navicat MySQL Data Transfer

Source Server         : 127.0.0.1
Source Server Version : 50711
Source Host           : localhost:3306
Source Database       : imcp_basic

Target Server Type    : MYSQL
Target Server Version : 50711
File Encoding         : 65001

Date: 2020-05-26 11:27:36
*/

SET FOREIGN_KEY_CHECKS=0;


-- 用户表
DROP TABLE IF EXISTS `USER`;
CREATE TABLE USER (
	`ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`GUID` VARCHAR(45) NOT NULL COMMENT '用户记录ID',
	`USERCODE` VARCHAR(45) NOT NULL COMMENT '用户编码',
	`USERNAME` VARCHAR(45) NOT NULL COMMENT '用户名称',
	`PASSWORD` VARCHAR(45) NOT NULL COMMENT '用户密码',
	`SEX` INTEGER NOT NULL COMMENT '性别 0男 1女',
	`EMAIL` VARCHAR(50) COMMENT '电子邮件',
  `USERBIRTH` DATETIME COMMENT '出生日期',
  `IDCARD` VARCHAR(20) COMMENT '身份证号',
  `MOBILENO` VARCHAR(50) COMMENT '手机',
  `ADDRESS` VARCHAR(50) COMMENT '家庭住址',
	`CREATEDATE` timestamp NOT NULL default current_timestamp COMMENT '创建日期',
	`STATUS` INTEGER NOT NULL COMMENT '状态 0激活 1关闭',
	`REMARK` VARCHAR(200) DEFAULT '' NULL COMMENT '备注',
	PRIMARY KEY (`ID`)
)
ENGINE = InnoDB DEFAULT CHARSET=utf8
COMMENT = '用户表';

-- 组织架构表
DROP TABLE IF EXISTS `ORG`;
CREATE TABLE ORG (
  `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `GUID` VARCHAR(45) DEFAULT '' NOT NULL COMMENT '组织ID',
  `ORGNAME` VARCHAR(40) DEFAULT '' NOT NULL COMMENT '组织名称',
  `PARENT`  VARCHAR(45) DEFAULT '' NOT NULL COMMENT '上级ID',
  `STATUS` INTEGER DEFAULT 0 NOT NULL COMMENT '状态 0开启 1关闭',
  `REMARK` VARCHAR(200) DEFAULT '' NULL COMMENT '备注',
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB DEFAULT CHARSET=utf8
COMMENT = '组织架构表';

-- 部门表
DROP TABLE IF EXISTS `DEPT`;
CREATE TABLE DEPT (
  `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `GUID` VARCHAR(45) DEFAULT '' NOT NULL COMMENT '部门ID',
  `DEPTNAME` VARCHAR(40) DEFAULT '' NOT NULL COMMENT '部门名称',
  `PARENT`  VARCHAR(45) DEFAULT '' NOT NULL COMMENT '上级ID',
  `STATUS` INTEGER DEFAULT 0 NOT NULL COMMENT '状态 0开启 1关闭',
  `REMARK` VARCHAR(200) DEFAULT '' NULL COMMENT '备注',
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB DEFAULT CHARSET=utf8
COMMENT = '部门架构表';

-- 角色表
DROP TABLE IF EXISTS `ROLE`;
CREATE TABLE ROLE (
  `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `GUID` VARCHAR(45) DEFAULT '' NOT NULL COMMENT '角色ID',
  `ROLENAME` VARCHAR(20) NOT NULL COMMENT '角色名称',
  `STATUS` INTEGER NOT NULL DEFAULT 0 COMMENT '状态 0开启 1关闭',
  `REMARK` VARCHAR(200) DEFAULT '' NULL COMMENT '备注',
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB DEFAULT CHARSET=utf8
COMMENT = '角色表';


-- 用户 角色 部门 组织 关系表
DROP TABLE IF EXISTS `USER_ROLE_DEPT_ORG`;
CREATE TABLE USER_ROLE_DEPT_ORG (
  `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `USERGUID` VARCHAR(45) DEFAULT '' COMMENT '用户ID',
  `ROLEGUID` VARCHAR(45) DEFAULT '' COMMENT '角色ID',
  `DEPTGUID` VARCHAR(45) DEFAULT '' COMMENT '部门ID',
  `ORGGUID` VARCHAR(45) DEFAULT '' COMMENT '组织ID',
  `STATUS` INTEGER NOT NULL DEFAULT 0 COMMENT '状态 0开启 1关闭',
  `REMARK` VARCHAR(200) DEFAULT '' NULL COMMENT '备注',
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB DEFAULT CHARSET=utf8
COMMENT = '角色表';