eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
    instance:
      instance-id: IMCP-SYSTEM-2050
      prefer-ip-address: true
logging:
    config: classpath:logback-spring.xml
mybatis:
    mapper-locations: mapper/*/*Mapper.xml
    type-aliases-package: com.imcp.system.bean
server:
    port: 2050
spring:
    application:
        datasource:
            driverClassName: com.mysql.jdbc.Driver
            password: root
            type: com.alibaba.druid.pool.DruidDataSource
            url: jdbc:mysql://localhost:3306/imcp_system?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
            username: root
        name: IMCP-SYSTEM
