eureka:
    client:
        serviceUrl:
            defaultZone: http://imcp-eureka-8761.com:8761/eureka,http://imcp-eureka-8762.com:8762/eureka,http://imcp-eureka-8763.com:8763/eureka
    instance:
        instance-id: imcp-consumer-2080.com # 在信息列表时显示主机名称  #host 文件需要配置 127.0.0.1  imcp-consumer-2080.com
        prefer-ip-address: true
logging:
    config: classpath:logback-spring.xml
server:
    port: 2080
spring:
    application:
        name: IMCP-CONSUMER
