#建议配置域名映射
#C:\Windows\System32\drivers\etc\host 配置内容
#127.0.0.1       imcp-eureka-8761.com
#127.0.0.1       imcp-eureka-8762.com
#127.0.0.1       imcp-eureka-8763.com
eureka:
    client:
        fetch-registry: true # 当然这个默认就是true，表示向eureka注册自己
        register-with-eureka: true # 这个的意思是从eureka server拉取注册表，集群中从相邻的eureka server拉取注册表
        prefer-ip-address: true     # 访问的路径变为IP地址
        service-url:
            defaultZone: http://imcp-eureka-8761.com:8761/eureka,http://imcp-eureka-8762.com:8762/eureka
    instance:
        hostname: imcp-eureka-8763.com
server:
    port: 8763
spring:
    application:
        name: imcp-eureka