eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
    instance:
      instance-id: IMCP-OBJECTS-2030
      prefer-ip-address: true
logging:
    config: classpath:logback-spring.xml
mybatis:
    mapper:
        identity: MYSQL
        mappers: com.imcp.objects.mapper
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.imcp.objects.bean

server:
    port: 2030
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
spring:
    application:
        name: IMCP-OBJECTS
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/imcp_objects?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: root

