/*
Navicat MySQL Data Transfer

Source Server         : 127.0.0.1
Source Server Version : 50711
Source Host           : localhost:3306
Source Database       : imcp_objects

Target Server Type    : MYSQL
Target Server Version : 50711
File Encoding         : 65001

Date: 2020-05-26 11:28:31
*/

SET FOREIGN_KEY_CHECKS=0;

-- 数据对象主表
DROP TABLE IF EXISTS OBJBASE;
CREATE TABLE OBJBASE (
  `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `GUID` VARCHAR(45) DEFAULT '' COMMENT '对象记录ID',
  `OBJVIEWNAME` VARCHAR(40) NOT NULL COMMENT '数据对象名',
  `OBJNAME` VARCHAR(40) NOT NULL COMMENT '数据对象物理名',
  `STATUS` INTEGER NOT NULL DEFAULT 1 COMMENT '数据对象状态 0启用 1不启用',
  `SCRIPT` TEXT COMMENT '对象脚本',
  `LOCKED` INTEGER NOT NULL DEFAULT 0 COMMENT '锁定对象 0开放 1锁定',
  `CREATEDATE` timestamp NOT NULL default current_timestamp COMMENT '数据对象创建日期',
  `REMARK` VARCHAR(200) DEFAULT '' NULL COMMENT '备注',
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB DEFAULT CHARSET=utf8
COMMENT = '数据对象主表';


-- 数据对象字段表
DROP TABLE IF EXISTS `OBJFIELD`;
CREATE TABLE OBJFIELD (
  `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `GUID` VARCHAR(45) DEFAULT '' COMMENT '字段记录ID',
  `OBJGUID` INTEGER NOT NULL COMMENT '对象ID',
  `FIELDVIEWNAME` VARCHAR(40) NOT NULL COMMENT '字段显示名',
  `FIELDNAME` VARCHAR(40) NOT NULL COMMENT '字段物理名',
  `FIELDPRIMARYKEY` INTEGER NOT NULL DEFAULT 1 COMMENT '是否是主键 0是 1否',
  `FIELDTYPE` VARCHAR(20) NOT NULL COMMENT '字段类型',
  `FIELDLENGTH` INTEGER NOT NULL DEFAULT 1 COMMENT '字段长度',
  `FIELDDEFAULT` VARCHAR(200) COMMENT '字段默认值',
  `FIELDFILLIN`  INTEGER NOT NULL DEFAULT 1 COMMENT '字段是否非空 0是 1否',
  `CREATEDATE` timestamp NOT NULL default current_timestamp COMMENT '字段创建日期',
  `REMARK` VARCHAR(200) DEFAULT '' NULL COMMENT '备注',
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB DEFAULT CHARSET=utf8
COMMENT = '数据对象字段表';

-- INTEGER
-- FLOAT
-- VARCHAR
-- TEXT
-- DATE
-- TIMESTAMP




